// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, plates;

  express = require('express');

  app = express();

  plates = require('express-plates').init(app);

  app.set('views', __dirname + '/views');

  app.get('/', function(req, res) {
    var friends, map;
    map = plates.Map();
    map.tag('title').use('title');
    map["class"]('target').to('content');
    map.where('id').is('title').to('title');
    map.where('data-content').is('name').to('name');
    map.where('href').is('/').insert('newURL');
    map.where('href').has(/aralbalkan/).insert('correctURLFragment');
    map.where('data-content').is('photo').use('aralImageURL').as('src');
    map["class"]('friend').use('friend');
    map["class"]('name').use('name');
    map["class"]('skills').use('skills');
    friends = true;
    if (friends) {
      map["class"]('no-friends-warning').remove();
    } else {
      map["class"]('friends-list').remove();
    }
    return res.render('simple', {
      data: {
        title: 'Express 3‐Plates sample',
        name: 'Express 3‐Plates',
        content: 'This is a simple example to demonstrate Express 3‐Plates.',
        newURL: 'http://aralbalkan.com',
        correctURLFragment: 'moderniosdevelopment',
        aralImageURL: 'http://aralbalkan.com/images/aral.jpg',
        friend: [
          {
            name: 'Laura',
            skills: 'design, development, illustration, speaking'
          }, {
            name: 'Seb',
            skills: 'particles, games, JavaScript, C++'
          }, {
            name: 'Natalie',
            skills: 'HTML, CSS'
          }
        ]
      },
      map: map
    });
  });

  app.listen(3000);

}).call(this);
